### ISSUE TITLE
Function of PV interneurons

### ISSUE THREAD

**Issue by AnjaRejc** [Eugene3dotdev/CN-2023-pr-MDD-snRNA-seq#11]
Nicely explained here: https://neuro.psychiatryonline.org/doi/10.1176/appi.neuropsych.21050136

**Comment by Louises99** [comment]
"PV interneurons, among other interneuron subtypes, are implicated in stress and depression with evidence for sex-specific changes ... and cellular stress may be part of the molecular pathology in MDD." (Maitra et al., 2023)

"Parvalbumin-expressing interneurons (PV-INs) are highly vulnerable to stressors and have been implicated in many neuro-psychiatric diseases such as schizophrenia, Alzheimer’s disease, autism spectrum disorder, and bipolar disorder." (Ruden et al., 2021)

Relevance for Major Depressive Disorder (MDD):
- in our paper they observed dysregulation in PV interneurons of female patients with MDD
- "We found evidence of dysregulated cellular stress pathways, such as heat-shock factor activation, in PV interneurons in MDD females."
- "The SLIT3 gene and its corresponding receptor gene ROBO2 were upregulated in PV interneurons and microglia respectively in females with MDD. Of note, genetic variation in SLIT3 has been associated with depression.

Maitra, M., Mitsuhashi, H., Rahimian, R. et al. Cell type specific transcriptomic differences in depression show similar patterns between males and females but implicate distinct cell types and genes. Nat Commun 14, 2912 (2023). https://doi.org/10.1038/s41467-023-38530-5

Ruden, J.B., Dugan, L.L. & Konradi, C. Parvalbumin interneuron vulnerability and brain disorders. Neuropsychopharmacol. 46, 279–287 (2021). https://doi.org/10.1038/s41386-020-0778-9
