### ISSUE TITLE
Next steps for the research

### ISSUE THREAD

**Issue by AnjaRejc** [Eugene3dotdev/CN-2023-pr-MDD-snRNA-seq#12]

**Comment by alex-prock** [comment]
see Limitations #2: The paper (Maitra 2023) notes that results about interaction of microglia with PV interneurons are speculative and thus: _Future studies using spatial transcriptomic techniques coupled with immunohistochemistry may better answer these questions._

**Comment by alex-prock** [comment]
also important from the Limitations #2: Any findings based on the datasets are not generalizable to all populations, given that samples are not from a diverse population (6 non-Caucasian female samples, 1 female sample of unknown ethnicity, rest Caucasian, including all male samples)
