### ISSUE TITLE
Presentation slides

### ISSUE THREAD

**Issue by AnjaRejc** [Eugene3dotdev/CN-2023-pr-MDD-snRNA-seq#13]

**Comment by alex-prock** [comment]
for content of **Next Steps** slide see #12 

regarding the **dataset** slide:
- two datasets, one published in 2020 with male samples and one published in 2022 with female samples
- datasets have same structure and contain cases (of MDD) and controls
- cells from post-mortem tissue from dorsolateral prefrontal cortex
- cases: MDD patients that died by suicide, controls: neurotypical subjects
- average of ~2200 cells per quality controlled sample (min 831, max 4479)

quality controlled samples (numbers in brackets are before data quality control):

| Samples | Case | Control |
|---|---|---|
| female | 9 (20) | 10 (18) |
| male | 11 (17) | 15  (17) |

**Comment by alex-prock** [comment]
data sample (matrix of cells and if genes are expressed in them):
![image](https://github.com/EugOT/CN-pr-MDD-snRNA-seq/assets/146839795/2177cef9-21a2-4e60-86ee-a0bd136dcfd2)

**Comment by AnjaRejc** [comment]
great, thank you very much, @alex-prock

**Comment by AnjaRejc** [comment]
[Research Model Proposal_V1_scRNAseq_MDD.pptx](https://github.com/EugOT/CN-pr-MDD-snRNA-seq/files/13424450/Research.Model.Proposal_V1_scRNAseq_MDD.pptx)

**Comment by AnjaRejc** [comment]
Final presentation - first version of the research model: 

[Research Model Proposal_V1_scRNAseq_MDD.pptx](https://github.com/EugOT/CN-pr-MDD-snRNA-seq/files/13424493/Research.Model.Proposal_V1_scRNAseq_MDD.pptx)
