### ISSUE TITLE
Selection of gene that determine the cell types 

### ISSUE THREAD

**Issue by AnjaRejc** [Eugene3dotdev/CN-2023-pr-MDD-snRNA-seq#15]
@EugOT  did we understand correctly? We have to select the gene(s) that determine the cell type? Or is it - determine single-cells that determine cell-type specific genes?

**Comment by Eugene3dotdev** [comment]
You should select features (genes), which are representative of cell types.

**Comment by AnjaRejc** [comment]
We determined cell types by the expression of the following three markers: ADAMTS17, ERBB4, DPP10. For the statistical analysis, we checked the following ten markers: ADAMTS17, ERBB4, DPP10, ZNF804A, MYO16, BTBD11, GRIA4, SLIT2, SDK1, PVALB (were given for the PValb cell type in data sets, provided on Github). @alex-prock this is really your contribution :)
