### ISSUE TITLE
Hypotheses

### ISSUE THREAD

**Issue by venhoffl98** [Eugene3dotdev/CN-2023-pr-MDD-snRNA-seq#5]
Based on the paper, what do we expect to find in the brain area and cell type we chose when comparing female to male depressive patients? Write hypotheses

**Comment by AnjaRejc** [comment]
sorry for jumping in, but i have a couple of proposals: 

-	For both papers : comparison: Deep layer excitatory neurons, astrocytes, and oligodendrocyte precursor cells in the prefrontal cortex are expected to show significant differences in gene expression between males and females with depression. 

OR Microglia and parvalbumin interneurons in the PFC are expected to show significant differences in gene expression between males and females with depression. 

-	just Nagy et al. paper: Female-first hypothesis: In females, microglia and parvalbumin (PV) interneurons are likely to contribute to the pathology of depression.

**Comment by Louises99** [comment]
Based on the findings from papers from Maitra et al. (2023) and Thippaiah et al. (2022), we propose the following hypothesis:
H1: Parvalbumin interneurons in the PFC are expected to show significant 	differences in gene expression between males and females with and without 	MDD (controls and cases groups).
