### ISSUE TITLE
Marker

### ISSUE THREAD

**Issue by venhoffl98** [Eugene3dotdev/CN-2023-pr-MDD-snRNA-seq#7]
What is a marker? Please save the paper you get the information from

**Comment by alexgrent** [comment]
Here some links to check out markers if found to map them to certain tissue: 

https://panglaodb.se/search.html?query=%22MTRNR2L12%22&species=3&tumor=0&nonadult=0 

https://www.proteinatlas.org/

**Comment by alexgrent** [comment]
Here some links to check out markers if found to map them to certain tissue: 

https://panglaodb.se/search.html?query=%22MTRNR2L12%22&species=3&tumor=0&nonadult=0 

https://www.proteinatlas.org/

**Comment by AnjaRejc** [comment]
Definition of a marker:
-	basically a specific gene or protein that is expressed in a particular cell type or is associated with the cell’s function. Markers in research are used to identify and isolate specific cell populations and look into their role in various e.g. diseases.

_*following definitions are mostly directly copy pasted from the papers, just so you don’t have to look through the entire paper for the relevant part of info:

Wikipedia: https://en.wikipedia.org/wiki/Neuronal_lineage_marker: 

-	Cell markers are valuable tools for examining the function of cells in normal conditions as well as during disease
-	To localize mRNA in brain tissue, one can use a fragment of DNA or RNA as a neuronal lineage marker, a hybridization probe that detects the presence of nucleotide sequences that are complementary to the sequence in the probe (in situ hybridization). Its application have been carried out in all different tissues, but particularly useful in neuroscience. Using this technique, it is possible to locate gene expression to specific cell types in specific regions and observe how changes in this distribution occur throughout the development and correlate with the behavioral manipulations.  

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3410725/ 
-	“marker genes” are associated with the defined cell types 
-	the anatomical distribution of marker genes provides further evidence that they are expressed in distinct cell type
