### ISSUE TITLE
Single cell RNA sequencing and workflow

### ISSUE THREAD

**Issue by venhoffl98** [Eugene3dotdev/CN-2023-pr-MDD-snRNA-seq#8]
What is single cell RNA sequencing? How would the work flow look?

**Comment by alexgrent** [comment]
You can find a good workflow for the analysis of scRNA seq data in the following tutorial:

https://satijalab.org/seurat/articles/pbmc3k_tutorial 

https://scanpy.readthedocs.io/en/stable/tutorials.html 
(this is already in use in the scripts)

**Comment by AnjaRejc** [comment]
A few more suggestions regarding scRNA-seq method: 
- https://genomemedicine.biomedcentral.com/articles/10.1186/s13073-017-0467-4 
* this paper is a great source of info on how to do actual scRNA-seq from basic steps, protocol choice to interpretation

- Mayer, Khakipoor, Drömer & Cozetto (2019). Single-cell RNA-Sequencing in Neuroscienc](https://www.degruyter.com/document/doi/10.1515/nf-2019-0021/html): nice explanation of the scRNA-seq workflow

**Comment by AnjaRejc** [comment]
Is this of any help: sc-RNA seq : Marker Identification  https://hbctraining.github.io/scRNA-seq_online/lessons/09_merged_SC_marker_identification.html
